Shoppy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls', namespace='products'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(
        r'^login/$',
        views.auth_login,
        name = 'authentication'
    ),
    url(
        r'^logout/$',
        auth_views.logout,
        {'next_page': '/'},
        name = 'logout'
    ),
    url(
        r'^$',
        views.ProducList.as_view(),
        name = 'ProducList'
    ),
    url(
        r'^product/(?P<pk>[0-9]+)/$',
        views.ProductDetail.as_view(),
        name='detail'
    ),
    url(
        r'^product/new',
        views.new_product,
        name='new_product'
    )
]

clients/models.py
from django.db import models
# from products.models import Product
# Create your models here.

class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.IntegerField(unique=True)
    email = models.EmailField(max_length=255,unique=True)
    address = models.CharField(max_length=255)
    # productos = models.ManyToManyField(Productos)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)

products/models.py
from django.db import models
from clients.models import Client
# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(blank = True)

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return self.name

class Favorite(models.Model):
    user = models.ForeignKey(Client)
    product = models.ForeignKey(Product)

    class Meta:
        verbose_name = 'Favorite'
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return '%s %s' %(self.user, self.product)

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

clients/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.shortcuts import (
                                render,
                                get_object_or_404,
                                redirect
                             )
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

from django.views.generic import ListView
from django.views.generic.detail import DetailView

from .forms import ProductForm
from .models import Product
from .mixins import AuthRedirectMixin
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ProducList(ListView):
    model = Product
# def hello_world(request):
#     # return HttpResponse('<h1>Hello World!</h1>')
#     # return render(request, 'index.html')
#     products = Product.objects.order_by('id')
#     template = loader.get_template('index.html')
#     context = {
#         'products': products,
#     }
#     return HttpResponse(template.render(context, request))

class ProductDetail(AuthRedirectMixin, DetailView):
    model = Product

# def product_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     template = loader.get_template('product_detail.html')
#     context = {
#         'product': product
#     }
#     return HttpResponse(template.render(context, request))

@login_required()
def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            product.save()
            return HttpResponseRedirect('/')
    else:
        form = ProductForm()
    template = loader.get_template('new_product.html')
    context = {
        'form': form
    }
    return HttpResponse(template.render(context, request))


def auth_login(request):
    context ={}
    template = loader.get_template('accounts/login.html')
    if request.method == 'POST':
        action = request.POST.get('action', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        if action == 'signup':
            repeat_password = request.POST.get('repeat_password', None)
            email = request.POST.get('email', None)
            first_name = request.POST.get('first_name', None)
            last_name = request.POST.get('last_name', None)
            if password == repeat_password:
                user = User.objects.create_user(username = username,
                                                password = password,
                                                email = email,
                                                first_name = first_name,
                                                last_name = last_name)
                try:
                    user.save()
                    user = authenticate(username = username, password=password)
                    login(request,user)
                    return redirect('/')
                except Exception as e:
                    context['signup_invalid']= True
                    context['error_message'] = 'Nombre de usuario ya registrado'
                    return HttpResponse(template.render(context, request))
            else:
                context['password_invalid']= True
                context['error_message'] = 'Las contraseñas no coinciden'
                return HttpResponse(template.render(context, request))
        elif action == 'login':
            user = authenticate(username = username, password=password)
            if user is not None:
                login(request,user)
                next_page = request.GET.get('next', None)
                print(next_page)
                if next_page:
                    return redirect(next_page)
                else:
                    return redirect('/')
            else:
                context['authenticate_invalid']= True
                context['error_message'] = 'Usuario o Contraseña incorrectos'
                return HttpResponse(template.render(context, request))
    context = {}
    return HttpResponse(template.render(context, request))

templates/accounts/login.html
{% extends "base.html" %}

{% block tittle %}Login{% endblock %}

{% block content %}
<div class="">
  <h2>login</h2>
  {% if authenticate_invalid %}
  <p>{{error_message}}</p>
  {% endif %}
  <form class="" method="post">
    {% csrf_token %}
    <input type="hidden" name="action" value="login"><br>
    <input type="text" name="username" value="" placeholder="Username" required><br>
    <input type="password" name="password" value="" placeholder="Password" required><br>
    <button type="submit" name="button">Log in</button>
  </form>
</div>
<div class="">
  <h2>Signup</h2>
  {% if password_invalid or signup_invalid %}
  <p>{{error_message}}</p>
  {% endif %}
  <form class="" method="post">
    {% csrf_token %}
    <input type="hidden" name="action" value="signup"><br>
    <input type="text" name="username" value="" placeholder="Username" required><br>
    <input type="password" name="password" value="" placeholder="Password" required><br>
    <input type="password" name="repeat_password" value="" placeholder="Repeat Password" required><br>
    <input type="text" name="first_name" value="" placeholder="First name" required><br>
    <input type="text" name="last_name" value="" placeholder="last_name" required><br>
    <input type="email" name="email" value="" placeholder="Email"><br>
    <button type="submit" name="button">Sign Up</button>
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>{% block tittle %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/new_product.html
{% extends "base.html" %}

{% block tittle %}
New product
{% endblock %}

{% block content %}
<h1>New product</h1>
<form class="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="button">Submit</button>
</form>
{% endblock %}

templates/products/product_detail.html
{% extends "base.html" %}


{% block tittle %}
{{ product.name }}
{% endblock %}

{% block content %}
<h1>{{ product.name }}:<br> ${{product.price}}</h1>
<h3>{{ product.category }}</h3>

<p>{{ product.description }}</p>
<img src="
    {% if product.image %}
      {{product.image.url}}
    {% endif %}
  " alt="img del producto:{{product.name}}">
{% endblock %}

templates/products/product_list.html
{% extends "base.html" %}

{% block tittle %}Hello World{% endblock %}

{% block content %}
<h1>Hola</h1>
{% if user.is_authenticated %}
<h3>{{user.username}} | <a href= "{% url "products:logout" %}" >Log out</a></h3>
{% else %}
<a href="{% url "products:authentication" %}">Login</a>
{% endif %}
<a href="{% url "products:new_product" %}">New Product</a>
<ul class="lista">
  {% for pr in object_list %}
    <li>
      {# <a href="{% url 'products.views.product_detail' pk=pr.pk %}">#}
      <a href="{% url "products:detail" pr.id %}">{{ pr.name }}</a>
      <p>{{pr.category}}</p>
        <img src="{% if pr.image %}{{pr.image.url}}{% endif %}" alt="img del producto:{{pr.name}}">
        {# <img src="{{pr.image.url}}" alt="img del producto:{{pr.name}}">#}
    </li>
  {% endfor %}
</ul>
{% endblock %}